//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;uzivatele&gt;
        ///&lt;citatele&gt;
        ///  &lt;citatel id=&quot;1&quot;&gt;
        ///    &lt;jmeno&gt;1&lt;/jmeno&gt;
        ///    &lt;prijmeni&gt;1&lt;/prijmeni&gt;
        ///    &lt;adresa&gt;1&lt;/adresa&gt;
        ///    &lt;telefon&gt;000 123 568&lt;/telefon&gt;
        ///    &lt;email&gt;1@1.com&lt;/email&gt;
        ///    &lt;datum_vytvoreni_uctu&gt;01.01.2012&lt;/datum_vytvoreni_uctu&gt;
        ///  &lt;/citatel&gt;
        ///  &lt;citatel id=&quot;2&quot;&gt;
        ///    &lt;jmeno&gt;2&lt;/jmeno&gt;
        ///    &lt;prijmeni&gt;2&lt;/prijmeni&gt;
        ///    &lt;adresa&gt;2&lt;/adresa&gt;
        ///    &lt;telefon&gt;000 123 568&lt;/telefon&gt;
        ///    &lt;email&gt;2@2.com&lt;/email&gt;
        ///
        ///    &lt;datum_vytvoreni_uctu&gt;01.01.2012&lt;/datum_vytvoreni_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uzivatele {
            get {
                return ResourceManager.GetString("uzivatele", resourceCulture);
            }
        }
    }
}
